# Generated by Django 4.2.7 on 2023-11-11 06:34

import core.models.auth
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('fio', models.CharField(max_length=200)),
                ('g_year', models.DateField(blank=True, null=True, verbose_name='Guvohnoma_Yili')),
                ('g_seria', models.DateField(blank=True, null=True, verbose_name='Guvohnoma_Seriasi')),
                ('g_ctg', models.CharField(max_length=25, verbose_name='Guvohnoma Categoryasi')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('user_type', models.SmallIntegerField(choices=[(1, 'Admin'), (2, 'User')], default=1)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', core.models.auth.UserM()),
            ],
        ),
    ]
