# Generated by Django 4.2.7 on 2023-11-13 12:26

import core.models.auth
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('fio', models.CharField(max_length=200)),
                ('g_year', models.DateField(blank=True, null=True, verbose_name='Guvohnoma_Yili')),
                ('g_seria', models.DateField(blank=True, null=True, verbose_name='Guvohnoma_Seriasi')),
                ('g_ctg', models.CharField(max_length=25, verbose_name='Guvohnoma Categoryasi')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('user_type', models.SmallIntegerField(choices=[(1, 'Admin'), (2, 'User')], default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', core.models.auth.UserM()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rental Cash', max_length=128)),
                ('number', models.CharField(max_length=20)),
                ('mask', models.CharField(blank=True, max_length=20, null=True)),
                ('expire', models.CharField(max_length=5)),
                ('token', models.CharField(max_length=256, unique=True)),
                ('balance', models.BigIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='cards')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Minitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_id', models.CharField(max_length=128, unique=True)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.SmallIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='core.card')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='core.card')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('raqam', models.CharField(max_length=15, verbose_name='Davlat raqam')),
                ('xk', models.TextField()),
                ('price', models.IntegerField(default=0, verbose_name='kunlik ijara')),
                ('status', models.BooleanField(default=True)),
                ('yili', models.IntegerField(verbose_name='Chiqarilgan yili')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Arenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=datetime.date(2023, 11, 13))),
                ('date_to', models.DateField(default='2023-11-014')),
                ('summa', models.BigIntegerField(default=0)),
                ('payt_type', models.CharField(choices=[('Naqd', 'Naqd'), ('Plastik', 'Plastik'), ('Bolib tolash', 'Bolib tolash')], max_length=50)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.car')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
