# Generated by Django 4.2.7 on 2023-11-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arenda',
            name='date_from',
        ),
        migrations.AddField(
            model_name='car',
            name='photos',
            field=models.ImageField(default=1, upload_to='cars'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arenda',
            name='date_to',
            field=models.DateField(default='2023-11-015'),
        ),
    ]
